### ISSUE TITLE
Exception raised from app code while firing Connection.onclose() ReferenceError: session is not defined

### ISSUE THREAD

**Issue by simecek-m** [lajosbencz/vue-wamp#21]
Getting this error in onclose callback. I think the problem is right here:
https://github.com/lajosbencz/vue-wamp/blob/cf09fd3f131d08196693398c90a2563ebb6b927f/src/Connection.js#L114

I don't have much time investigate it atm but I believe there should be `config.onclose(reason, details); `.. maybe? 🤔

**Comment by lajosbencz** [comment]
Thanks for the feedback, you are correct!
Fixed in 2.0.6

**Comment by simecek-m** [comment]
I think you forgot to rebuild it after the fix. There is still
https://github.com/lajosbencz/vue-wamp/blob/9070a0c247935fde33ae38e18e30fb858c30017f/dist/vue-wamp.esm.js#L314
in the dist folder.

**Comment by lajosbencz** [comment]
Strange, i've built and published it, but you are right, it was still the wrong version... i probably messed up something else.

I've pushed a v2.10 version, it is definitely fixed now, i've also ran ```npm audit fix``` to refresh the dependencies to the latest versions.

Thanks for the feedback, i'll reopen the issue.
Could you close it, if this version fixes it for you?

**Comment by simecek-m** [comment]
Yes, everything is OK now. Thank you 👍
